# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  if ENV["http_proxy"]
    puts "http_proxy: " + ENV["http_proxy"]
    config.proxy.http     = ENV["http_proxy"]
  end
  if ENV["https_proxy"]
    puts "https_proxy: " + ENV["https_proxy"]
    config.proxy.https    = ENV["https_proxy"]
  end
  if ENV["no_proxy"]
    config.proxy.no_proxy = ENV["no_proxy"]
  end

  config.ssh.username = "root"
  # config.ssh.password = "vagrant"

  config.vm.define "nokia-dev-kub-master" do |a|
	  a.vm.provider "docker" do |d|
	    # Change below value to any other docker image to start/run the container
	    d.image = "raju2210/dev-workstation"
	    d.privileged = true
	    d.remains_running = true
      # Change below value to mount volumes
	    #d.volumes = ["/dev/macfuse0:/dev/fuse"]
	    d.has_ssh = true
	    d.ports = ["9090:91"]
	  end
   end
end
