name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore: release')"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKERFILE_HADOLINT_FILE_NAME: .hadolint.yaml
          FILTER_REGEX_EXCLUDE: .*src/.*VagrantDockerfile
      - name: Cache .m2 registry
        uses: actions/cache@v2.1.4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Build with Maven
        run: |
          SNAP_VERSION="$(cat version.txt | awk -F. -v OFS=. '{$NF++;print}')-SNAPSHOT"
          mvn -B package --file pom.xml -Drevision=${SNAP_VERSION} \
            -Djkube.docker.username=${{ secrets.DOCKER_HUB_USERNAME }} \
            -Djkube.docker.password=${{ secrets.DOCKER_HUB_PASSWORD }} \
            -Djkube.docker.verbose=true
      - name: Publish to GitHub Packages Apache Maven
        run: |
          SNAP_VERSION="$(cat version.txt | awk -F. -v OFS=. '{$NF++;print}')-SNAPSHOT"
          mvn deploy --file pom.xml -s $GITHUB_WORKSPACE/settings.xml -Drevision=${SNAP_VERSION} \
            -Djkube.docker.username=${{ secrets.DOCKER_HUB_USERNAME }} \
            -Djkube.docker.password=${{ secrets.DOCKER_HUB_PASSWORD }} \
            -Djkube.docker.verbose=true
        env:
          GITHUB_TOKEN: ${{ github.token }}
